# Generated by Django 5.2.3 on 2025-06-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_response'),
    ]

    operations = [
    ]
