# Generated by Django 5.2.3 on 2025-06-20 18:14

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='response',
            name='text',
        ),
        migrations.AddField(
            model_name='response',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Текст отклика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
