# Generated by Django 5.2.3 on 2025-06-26 11:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_rename_views_count_post_views_remove_response_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема рассылки')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание рассылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено?')),
            ],
            options={
                'verbose_name': 'Новостная рассылка',
                'verbose_name_plural': 'Новостные рассылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
